name: Setup node project
description: Checks out code, sets up Node and installs the dependencies

inputs:
  node-version:
    description: NodeJS version to use
    required: false
    default: '22'

outputs:
  actual-node-version:
    description: Actual granular NodeJS version used
    value: ${{ steps.capture-version.outputs.actual-node-version }}

runs:
  using: 'composite'
  steps:
    - name: Set up nodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Capture actual node version
      id: capture-version
      run: echo "actual-node-version=$(node --version)" >> $GITHUB_OUTPUT
      shell: bash
