name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual deployment'
        required: true
        type: string

jobs:
  logging:
    uses: './.github/workflows/logging.yml'
    with:
      stand-name: 'Za Warudo'
  test:
    name: Install and test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup nodeJS project
        uses: ./.github/actions/setup-node-project
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: npm test -- --ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ matrix.node-version }}
          path: dist/

  deploy:
    name: Deploy to Azure app services
    runs-on: ubuntu-latest
    needs: test
    environment: production
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: deploy-prod
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup nodeJS project
        uses: ./.github/actions/setup-node-project
        with:
          node-version: '22'

      - name: Log deployment
        run: echo "Manual deploy triggered. Reason- ${{ inputs.reason }}"

      - name: Test annotation
        run: echo "::notice::Deploy job started successfully on environment production"

      - name: Download build artifact from test job
        uses: actions/download-artifact@v4
        with:
          name: build-output-22
          path: dist/

      - name: Deploy to Azure web app
        uses: azure/webapps-deploy@v3
        with:
          app-name: task-manager-actions
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
