name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual deployment'
        required: false
        type: string
        default: 'just because'

jobs:
  logging:
    uses: './.github/workflows/logging.yml'
    with:
      stand-name: 'Za Warudo'
  test:
    name: Install and test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Report package info
        id: pkg-report
        uses: ./.github/actions/package-reporter

      - name: Setup nodeJS project
        id: node-setup
        uses: ./.github/actions/setup-node-project
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: npm test -- --ci

      - name: Build
        run: npm run build

      - name: Write build summary
        uses: ./.github/actions/build-summary
        with:
          node-version: ${{ steps.node-setup.outputs.actual-node-version }}
          test-result: 'passed'

      - name: Log installed Node version
        run: echo "Actual node version installed was ${{ steps.node-setup.outputs.actual-node-version }}"
